### ISSUE TITLE
compute_halo_properties.py fails for DMO runs.

### ISSUE THREAD

**Issue by jemme07** [SWIFTSIM/SOAP#25]
compute_halo_properties.py fails for the latest subhalo ranking branch for DMO runs with the following message:

```
Traceback (most recent call last):
  File "/snap8/scratch/dp004/fkgm22/SOAP//compute_halo_properties.py", line 497, in <module>
    compute_halo_properties()
  File "/snap8/scratch/dp004/fkgm22/SOAP//compute_halo_properties.py", line 433, in compute_halo_properties
    metadata = task_queue.execute_tasks(
  File "/snap8/scratch/dp004/fkgm22/SOAP/task_queue.py", line 195, in execute_tasks
    result.append(task(*args))
  File "/snap8/scratch/dp004/fkgm22/SOAP/chunk_tasks.py", line 265, in __call__
    total_time, task_time, nr_left, nr_done = process_halos(comm, cellgrid.snap_unit_registry, data, mesh,
  File "/snap8/scratch/dp004/fkgm22/SOAP/halo_tasks.py", line 300, in process_halos
    halo_result = process_single_halo(
  File "/snap8/scratch/dp004/fkgm22/SOAP/halo_tasks.py", line 116, in process_single_halo
    idx_he, idx_T, idx_n, t_z, d_z, t_T, d_T, t_nH, d_nH, t_He, d_He, abundance_to_solar, joint_mask, volumes, data_n = xray_calc.find_indices(particle_data[ptype]['Densities'], particle_data[ptype]['Temperatures'], particle_data[ptype]['SmoothedElementMassFractions'], particle_data[ptype]['Masses'], fill_value = 0)
KeyError: 'PartType0'
```

The submission script can be found here:

`/snap8/scratch/dp004/fkgm22/SOAP/scripts/FLAMINGO/L1000N1800`

@Joeybraspenning, it might be related to the addition of the xray_calculator

**Comment by MatthieuSchaller** [comment]
Fixed by #26.
